### PR TITLE
fix typo signle

### PR DESCRIPTION
**Pull request by flamingbear**
Nothing special

### CODE REVIEW

**Comment by flamingbear** [comment]
I was hoping to correct the exercise in "Classes" as well.  I was unable to return "hello ${var}" but needed to use "hello " + var, or maybe it was bye, but in any case, I didn't find the exercises to modify.

**Comment by hendrikswan** [comment]
Hi Matt (@flamingbear), 

Thanks for being the first one to do a pull request! You rock! 

The exercises themselves are currently not open sourced. Up to this point people only expressed interest in making changes to the instructional material, so I wanted to see whether there is interest in making changes to the exercises themselves before open sourcing them. 

I'll work on getting them into this repo too, and will let you know when I've done so! 

Thanks
Hendrik

**Comment by hendrikswan** [comment]
Matt, can I please get your twitter handle? I would like that to be
displayed on your profile on tagtree.io if you don't mind.

**Comment by flamingbear** [comment]
sure thing @matthewsavoie is my twitter handle.

**Pull request merged**
