### PR TITLE
Update background.md

### PR DESCRIPTION
**Pull request by soundyogi**
whitespace, let is the new var

### CODE REVIEW

**Comment by hendrikswan** [comment]
I prefer the old school code to use var, it makes it clearer that it's old school. What do you think?

**Comment by soundyogi** [comment]
Ahhh sorry! You are completely right! Changed it.

editing rage ^^;

**Comment by hendrikswan** [comment]
hehe, cool.

**Comment by hendrikswan** [comment]
What is your twitter handle? I haven't gotten around to slotting this in
nicely on tagtree, but once I get arround to do the work it will be nice to
have it.

**Comment by soundyogi** [comment]
Uh i guess @soundyogi, just starting to get active again ^^;

**Comment by soundyogi** [comment]
btw: http://tagtree.io/ is down

perhaps we should pass on those 

for(;;){} loops 

I hope your sandboxes are.. well sandboxed ^^;

**Comment by hendrikswan** [comment]
Weird.. Thanks for letting me know. Yeah it's sandboxed, but it's probably some other exception that's not handled properly.

**Pull request merged**
